"use client";
import { ScrollArtwork } from "../visual/ScrollArtwork";
import { ReelsStrip } from "../video/sections/ReelsStrip";
import { CONCEPTS } from "../bong/BongConcept";
import { LEARNINGS as BONG_LEARNINGS } from "../bong/BongLearnings";
import { SPECS } from "../bong/BongPremise";
import { BongDiagram } from "./PreservedBlocks";
import { KEYFRAMES } from "../bong/BongKeyframes";
import { Coverflow } from "../Coverflow";
import { AruWalk } from "../aru/AruWalk";
import { FeatureClip, YouTubeEmbed } from "./InlineMedia";
import { Assembly } from "../home/Assembly";
import { useState } from "react";
import { SOURCES, POSTER, YT, REELS_IG, CUTS, TOOLING, REFERENCES, REFERENCE_CREDIT, LEARNINGS } from "@/lib/aruData";
import { TVC_CROWNED, TVC_ALSO, PROJECT_TVC, COMMERCIAL, CAMPAIGNS, MUSIC, EVENTS, REELS, thumb, type Film as FilmData } from "@/lib/videoData";
import { VideoLightbox } from "../VideoLightbox";
import { CaseChapters } from "../CaseOpening";
import { Story, Chapter, Heading, Action, Picture, Film, Process, Notes, s } from "./StoryKit";

function CinemaHero({ title, label, image, children, href }: { title: string; label: string; image: string; children: React.ReactNode; href: string }) {
  return <section data-zone="dark" className={s.cinematicHero}><img src={image} alt="" fetchPriority="high"/><div><a href="/" className={s.label}>← Selected work / {label}</a><h1>{title}</h1><p>{children}</p><Action href={href}>Enter the project</Action></div></section>;
}
export function AruStory() {
  const [selected,setSelected]=useState(0);
  const shot=SOURCES[selected];
  const [cut,setCut]=useState(0);
  return <Story next="aru"><CinemaHero title="Aru Otoko." label="AI film / 2026" image={POSTER.horizontal} href="#film">A man caught in the pace of the city. A 33-second music video shaped through image direction, motion and the rhythm of the edit.</CinemaHero><CaseChapters links={[["#film","The film"],["#shots","Inside the frames"],["#pipeline","The edit"],["#learnings","Reflections"]]}/>
    <Chapter id="film"><Heading n="01 / Watch first" title="The city rushes." accent="He stays still."><p>Eleven fixed-length generations became a short film. The final pace was made in the edit, with deliberate cuts and speed changes.</p></Heading><YouTubeEmbed id={YT.hero!} title="Aru Otoko, final music video"/><div className={s.stats}><div><strong>33s</strong><span>Final film</span></div><div><strong>136</strong><span>Beats per minute</span></div><div><strong>11</strong><span>Generations</span></div><div><strong>5.04s</strong><span>Each source clip</span></div></div></Chapter>
    <div data-zone="dark" className={s.retained}><AruWalk compact/></div>
    <Chapter id="shots" light className={s.compactHeading}><Heading n="02 / Direction, frame by frame" title="A consistent world." accent="A specific feeling."><p>Explore the source frames and raw clips. Some were left out of the final edit; selection mattered as much as generation.</p></Heading><div className={s.shotTabs} aria-label="Choose a source shot">{SOURCES.map((source,i)=><button key={source.id} aria-pressed={i===selected} onClick={()=>setSelected(i)}>{source.label} · {source.title}</button>)}</div><div className={`${s.split} ${s.wide}`}><div>{shot.youtube?<YouTubeEmbed key={shot.id} id={shot.youtube} title={`${shot.label}: ${shot.title}`}/>:<Picture src={shot.still} alt={shot.title}/>}</div><div><h3>{shot.title}</h3><p>{shot.content}</p>{shot.note&&<p>{shot.note}</p>}<Notes rows={[["Image direction",shot.imgPrompt||"The source follows the film’s shared character and visual direction."],["Motion direction",shot.motPrompt||"Motion was developed within the shared visual language of the film."]]}/></div></div></Chapter>
    <Chapter id="pipeline" className={`${s.compactChapter} ${s.compactHeading} ${s.compactProcess}`}><Heading n="03 / Generation is the beginning" title="The rhythm was" accent="a human decision."><p>Consistent character direction held the frames together. Editing turned separate clips into a progression with intention.</p></Heading><ScrollArtwork variant="edit" images={["s01-back","s05-rooftop","s06-vending"].map(x=>({src:`/images/aru-otoko/stills/${x}.webp`,alt:`Aru Otoko directed frame ${x}`}))}/><Process steps={[["Visual language","Comic shading, ink, halftone texture and a restrained warm palette define the world."],["Character continuity","A fixed wardrobe and repeated character direction hold the protagonist across shots."],["Motion generation","Nano Banana 2 image direction feeds Seedance motion exploration."],["The cut","CapCut editing, speed ramps and beat-aware cuts establish the final rhythm."]]}/><div className={s.timeline}><span className={s.label}>Inside the cut / Select a moment</span><div>{CUTS.map((item,i)=><button key={i} aria-pressed={cut===i} onClick={()=>setCut(i)}><b>{item.label}</b><span>{item.speed}×</span></button>)}</div><p aria-live="polite">{CUTS[cut].note}</p><small>Sequence and speed multipliers reconstructed from the edit. Blocks do not represent exact durations.</small></div><div className={s.wide}><details className={s.notes}><summary>Explore the original production canvas</summary><Picture src={TOOLING.screenshot} alt="Original Aru production workflow canvas"/></details></div></Chapter>
    <Chapter id="vertical" light className={s.compactHeading}><Heading n="04 / Other cuts & the making" title="The film, reframed." accent="The process, explained."/><div className={s.duo}><YouTubeEmbed id={YT.vertical!} title="Aru Otoko vertical cut" vertical/><div><h3>Behind the film</h3><div className={s.verticalEmbed}><iframe src={`${REELS_IG.permalink}embed/`} title="Aru Otoko process reel" loading="lazy" style={{width:"100%",height:"100%",border:0}} allowFullScreen/></div><Action href={REELS_IG.permalink}>Open the process reel</Action></div></div></Chapter>
    <Chapter id="learnings" light><div className={s.socials}>{REFERENCES.map(ref=><Picture key={ref.src} src={ref.src} alt={ref.label} caption={ref.note}/>)}</div><p className={s.caption}>{REFERENCE_CREDIT}</p><Notes rows={LEARNINGS.map(item=>[item.title,item.body])}/><Heading n="05 / What stayed with me" title="More control." accent="Fewer assumptions."/><Notes rows={[["Direct the world before the shot","A shared palette, texture and character definition gave the generations something consistent to return to."],["Let the edit reject good-looking footage","A visually strong source clip can still weaken the sequence. Unused explorations remain available here because they show the selection process."],["Motion needs editorial judgement","The model returned fixed-length clips. Timing, emphasis and the relation to the music came from the cut, rather than the generation duration."]]}/></Chapter>
  </Story>;
}
const keys=["kf1-the-gate-at-dawn","kf2-the-wanderer-enters","kf3-path-of-guardians","kf4-the-kneeling-moment","kf5-after-the-recognition"];
export function BongStory() {
  return <Story next="bong"><CinemaHero title="Bóng Vespera." label="Art direction / AI campaign study" image="/images/vng-demo/stills/kf1-the-gate-at-dawn.webp" href="#final">A fictional RPG campaign built around a single visual world, carried from concept to artwork and motion.</CinemaHero><CaseChapters links={[["#final","The campaign"],["#keyframes","World building"],["#motion","Motion studies"],["#pipeline","The process"]]}/>
    <Chapter id="final" light><div className={s.split}><Picture src="/images/vng-demo/final/ad-mockup-final.webp" alt="Bóng Vespera final campaign artwork" portrait/><div><span className={s.label}>01 / The finished piece</span><h2>A world worth<br/><em>stepping into.</em></h2><p>A solitary traveller, monumental guardians and a moment of recognition. The image system connects atmosphere, character and campaign typography.</p><div className={s.stats}><div><strong>4</strong><span>AI models</span></div><div><strong>6h</strong><span>Production window</span></div></div><p>Keyframe 5 became the background. A GPT Image logotype was composited in Figma Weave, with an unprompted ornamental flourish kept in the final artwork.</p><p className={s.caption}>Self-directed fictional campaign study, created on the free tier.</p></div></div></Chapter>
    <Chapter id="concept" light className={s.compactHeading}><Heading n="02 / Concept development" title="Three directions." accent="One selected world."/><ScrollArtwork variant="world" images={keys.slice(0,3).map(x=>({src:`/images/vng-demo/stills/${x}.webp`,alt:"Bóng Vespera keyframe study"}))}/><Notes visible rows={SPECS}/><div className={s.concepts}>{CONCEPTS.map((c,i)=><article key={c.dir} data-picked={c.pick||false}><div className={s.conceptMark} aria-hidden="true">{String.fromCharCode(65+i)}</div><span className={s.label}>{c.dir}</span>{c.pick&&<strong className={s.selectedBadge}>Selected direction ↗</strong>}<h3>{c.title}</h3><p>{c.desc}</p><dl><dt>Mood</dt><dd>{c.mood}</dd><dt>Audience</dt><dd>{c.target}</dd></dl></article>)}</div><p className={s.choiceNote}>C was selected for its quiet atmosphere and a single recurring subject, a visual direction that could stay coherent within the available generation budget.</p></Chapter><Chapter id="keyframes"><Heading n="03 / Building the visual world" title="One atmosphere." accent="Five moments."><p>The keyframes develop the traveller’s journey through scale, light and a consistent sense of place.</p></Heading><div data-preserved="bong-coverflow"><Coverflow itemClassName="w-[min(75vw,440px)]" items={KEYFRAMES.map(k=><div key={k.no} className={s.keyframeCard}><Picture src={k.img} alt={k.title}/><h3>{k.title}</h3><span className={s.label}>{k.credit}</span><p>{k.lesson}</p></div>)}/></div></Chapter>
    <Chapter id="motion" light><Heading n="04 / Stillness into movement" title="The world moves." accent="The mood stays."><p>Two motion explorations test how much movement the visual language can carry without losing its atmosphere.</p></Heading><div className={s.duo}><FeatureClip index={0} description="Two related keyframes hold the motion together: a slow dolly-out, drifting mist and a steady ember pulse." poster={`/images/vng-demo/stills/${keys[2]}.webp`} src="/images/vng-demo/motion/motion-kf3-to-kf5-seedance.mp4" title="Guardians to recognition"/><FeatureClip index={1} description="All five keyframes were chained together. The scene jumps break continuity, showing where this approach falls short." poster={`/images/vng-demo/stills/${keys[0]}.webp`} src="/images/vng-demo/motion/motion-multiframes-experimental.mp4" title="Multi-frame motion exploration"/></div></Chapter>
    <Chapter id="pipeline"><Heading n="05 / Directing the handoffs" title="Different tools." accent="One creative intent."><p>The challenge was to keep the idea coherent across concept development, imagery, typography and motion.</p></Heading><Process steps={[["Develop","Claude expands the brief into a visual concept and production direction."],["Generate","Flux develops the keyframes and the world’s visual consistency."],["Compose","GPT Image typography and compositing bring the campaign artwork together."],["Animate","Seedance explores movement between the selected frames."]]}/><BongDiagram/><Notes visible rows={BONG_LEARNINGS.map(item=>[item.title,item.body])}/><Picture src="/images/vng-demo/workflow/weave-canvas-full.webp" alt="The actual Bóng Vespera workflow canvas" caption="Working canvas, from concept to production"/><div className={s.wide}><Notes rows={[["The hardest handoff","Each tool could produce an attractive output. The directing work was making those outputs belong to the same campaign."],["What the still frames established","Scale, lighting and the traveller’s relationship to the guardians created the foundation for both artwork and motion."],["What I would refine next","A longer production pass would focus on motion continuity and compositing polish while keeping the visual direction intact."]]}/></div></Chapter>
  </Story>;
}

export { VideoArchive as VideoStory } from "../video/VideoArchive";
