"use client";
import { ScrollArtwork } from "../visual/ScrollArtwork";
import { TerraDiagrams, TerraScopeDetails, TerraFilms, IeltsDiagrams, CareBoundaries } from "./PreservedBlocks";
import { CareMechanism } from "./CareMechanism";
import { FEATURES } from "../nhaminh/NhaMinhAllFeatures";
import { METRICS } from "../nhaminh/NhaMinhNumbers";

import { TerraBroke } from "../terra/TerraBroke";
import { YouTubeEmbed, FeatureClip } from "./InlineMedia";
import { FeatureShowcase } from "./FeatureShowcase";
import { useState } from "react";
import { CaseOpening, CaseChapters } from "../CaseOpening";
import { WorkflowVisual, CareIllustration } from "../home/WorkflowVisual";
import { Story, Chapter, Heading, Action, Picture, Film, Process, Notes, s } from "./StoryKit";

export function TerraStory() {
  return <Story next="terra"><div data-zone="dark"><CaseOpening project="terra" /><CaseChapters links={[["#systems","Workplace applications"],["#results","Results"],["#pages","Website & creative"],["#terra-films","Film"]]} /></div>
    <Chapter id="systems"><Heading n="01 / Applications built for the team" title="Make it once." accent="Make it repeatable."><p>The goal was to remove repeated production work so a non-technical team could publish and report independently.</p></Heading><ScrollArtwork variant="publishing"/><WorkflowVisual/><TerraDiagrams/><TerraScopeDetails/><Process illustrated steps={[["Page Publisher","HTML layouts become Elementor pages, with WebP images and AI-assisted alt text."],["HR Column Publisher","Word documents become structured bilingual articles with SEO fields prepared in one pass."],["Reporting","Search Console, GA4 and PageSpeed signals feed a common reporting workflow."],["Iteration","Performance and production friction inform the next useful improvement."]]}/><Notes rows={[["What changed for the team","A publishing workflow that previously took roughly one hour could be initiated with one click. The point was less manual rebuilding and more consistent output."],["Where AI helped","AI handled repeatable enrichment and first-pass preparation. The editorial structure, visual decisions and final checks remained directed work."],["What I would carry forward","Treat the publishing workflow as part of the product. A polished page matters, but so does whether another person can reliably make the next one."]]}/></Chapter>
    <Chapter id="results" light><Heading n="02 / What changed" title="Small decisions." accent="Compounding results."><p>From the launch baseline to a 2,137-click daily peak. The work connected acquisition, content, site experience and the way the team published.</p></Heading><div className={s.stats}>{[["12×","Organic growth"],["31.4M","Search impressions"],["978","Keywords in the top 10"],["55 → 90","Site health"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><svg className={s.chart} viewBox="0 0 600 180" preserveAspectRatio="none" role="img" aria-label="Monthly organic search clicks from the existing case study reporting"><path d="M0,162.2 L37.5,155.7 L75,148.4 L112.5,136.3 L150,131.7 L187.5,140.4 L225,144.5 L262.5,135.5 L300,63.5 L337.5,35 L375,108.7 L412.5,104.5 L450,57.5 L487.5,32.3 L525,100.1 L562.5,12 L600,128.2" stroke="currentColor" strokeWidth="3" fill="none" pathLength="1"/></svg><p className={s.caption}>Monthly organic clicks: December 2024 to April 2026, a 17-month Search Console window. 449,965 total clicks; peak 66.3K in March 2026. The wider role ran September 2024 to June 2026.</p><div className={`${s.split} ${s.wide}`}><p className={s.quote}>One person connecting the brief, the creative and the system behind it.</p><div><h3>The brief was broader than traffic.</h3><p>Help FDI buyers understand a B2B payroll and HR offer, build trust in English and Vietnamese, and give a small team a repeatable way to ship.</p><p>My scope crossed content architecture, technical SEO, landing pages, creative assets, paid coordination and reporting.</p></div></div></Chapter>
    <Chapter id="pages"><Heading n="03 / A clearer digital front door" title="Built around" accent="the buyer’s questions."><p>Service pages, product explanations and proof each play a different role. The site had to make a complex offer easier to navigate.</p></Heading><div className={s.browserGrid}>{["outsourcing","hrsystem","compliance","customers"].map(name=><a className={s.browser} key={name} href={`https://terra-plat.vn`} target="_blank" rel="noreferrer" aria-label={`Explore terra ${name} website`}><img src={`/images/terra-${name}-preview.webp`} alt={`terra ${name} page`} loading="lazy"/></a>)}</div><p className={s.caption}>Hover a page to explore its full length. Select a preview to visit terra.</p></Chapter>
    <Chapter id="social" light><Heading n="04 / Brand in everyday use" title="Useful information." accent="A recognisable voice."><p>Law updates, service explainers and culture posts brought a consistent visual language to very different communication needs.</p></Heading><div className={s.socials}>{["02-law-update-econtract-vi","05-service-explainer-si-expat","07-event-recap-terra-say-hi","04-seasonal-womens-day","03-culture-appreciation-party","06-culture-team-photo"].map((f,i)=><Picture key={f} src={`/images/terra-social/${f}.webp`} alt={`terra social creative ${i+1}`} caption={["Regulatory content","Service education","Event storytelling","Seasonal communication","Team culture","People behind the brand"][i]}/>)}</div></Chapter>
    <Chapter id="terra-films" light><Heading n="05 / Film & short-form" title="The brand," accent="in motion."/><TerraFilms/></Chapter>
    <Chapter id="reflection" light><div className={s.retained}><TerraBroke/></div></Chapter>
  </Story>;
}

const demos = [
 ["Together","01_Dual_Screen_Realtime_Sync_RealUI_1080p"], ["Medication","02_App_BaMe_Lich_Uong_Va_Tu_Thuoc_RealUI_1080p"], ["Cháu Bi","03_App_BaMe_Chau_Bi_AI_Voice_RealUI_1080p"], ["Voice call","04_Dashboard_Con_InApp_Voice_Call_RealUI_1080p"], ["Health trends","05_Dashboard_Con_Vital_Line_Chart_RealUI_1080p"], ["Family profiles","06_Dashboard_Con_Multi_Profile_Switcher_RealUI_1080p"], ["Google tools","07_Dashboard_Con_Google_Ecosystem_RealUI_1080p"], ["Prescription OCR","08_Dashboard_Con_Gemini_Vision_OCR_RealUI_1080p"],
];
export function NhaStory() {


  return <Story next="nha"><div data-zone="light"><CaseOpening project="nha"/><CaseChapters links={[["#experience","See it working"],["#interfaces","Two generations"],["#care-system","AI with boundaries"]]}/></div>
    <Chapter id="experience"><Heading n="01 / The product in use" title="See the complete" accent="experience."><p>The full walkthrough connects the features into one family-care experience. Choose a feature below to see a short loop of the interaction.</p></Heading><YouTubeEmbed id="5CNx1tlCGSM" title="Nhà Mình full app demonstration"/><Action href="https://ai-riser-namdosan-fa737.web.app">Try the live app</Action><FeatureShowcase demos={demos} descriptions={[
      "A parent confirms a dose and the caregiver receives the update in the same shared care flow.",
      "A daily medication schedule and visual medicine cabinet keep the next action clear.",
      "Cháu Bi offers a familiar Vietnamese voice interface for questions and everyday assistance.",
      "A caregiver can move from an alert to an audio call with their parent.",
      "Health indicators are plotted over time so a caregiver can review changes in context.",
      "Switch between family members while keeping their records and routines separate.",
      "Google Calendar and Tasks support appointments and care reminders.",
      "Gemini Vision extracts prescription details into a structured view for review."
    ]}/></Chapter>    <Chapter id="interfaces" light><Heading n="02 / One family, two experiences" title="Different needs." accent="Shared care."><p>Parents need a calm, legible interface. Their children need context, changes and a way to stay connected.</p></Heading><div className={s.appStage}><img src="/images/nha-minh/01-trang-chao-hero.png" alt="Nhà Mình desktop homepage" loading="lazy"/><img src="/images/nha-minh/07-app-bame-hom-nay.png" alt="Parent medication check-in" loading="lazy"/></div><div className={`${s.split} ${s.wide}`}><div><h3>Designed around the person using it.</h3><p>Large actions and everyday Vietnamese language keep the parent experience focused. The dashboard collects the detail a caregiver needs without putting that complexity on the parent.</p></div><CareIllustration/></div><div className={`${s.mosaic} ${s.wide}`}><Picture src="/images/nha-minh/09-app-bame-chau-bi.png" alt="Cháu Bi voice companion" portrait caption="A familiar way to ask for help"/><Picture src="/images/nha-minh/04-app-con-chi-so.png" alt="Family health indicators dashboard" caption="Health information in context"/></div></Chapter>
    <Chapter id="care-context" light><Heading n="03 / From input to everyday care" title="Complex behind the scenes." accent="Simple in the hand."><p>One shared record connects two interfaces. Parents get a clear next action; family members get the context to help.</p></Heading><ScrollArtwork variant="care"/><CareMechanism/><CareBoundaries/></Chapter>
    <Chapter id="care-system"><Heading n="04 / Directing the intelligence" title="Helpful AI." accent="Clear boundaries."><p>The experience combines prescription reading, voice interaction and family coordination. It is designed to support care, not replace clinical judgement.</p></Heading><Process steps={[["Read","Gemini Vision extracts information from a prescription image."],["Review","Structured information is presented for review, rather than silently treated as fact."],["Remind","Medication routines and Google Workspace connections help organise daily care."],["Connect","Check-ins give family members a shared view of what is happening."]]}/><Notes rows={[["Safety is part of the interaction","The project sets boundaries against unauthorised diagnosis or dosage alteration. AI output can be wrong, so extracted prescription information needs review."],["Why two interfaces","One dense dashboard would make the parent experience harder. Separating parent and caregiver modes lets each person see the actions that matter to them."],["My role","I directed the product concept, user experience and AI-assisted implementation, connecting the model capabilities to a practical family-care flow."],["What this project is","An AI Riser Vietnam 2026 project and product demonstration. It should not be read as evidence of clinical validation or patient outcomes."]]}/><Action href="https://github.com/jak3rpham/ai-riser-namdosan">Explore the project source</Action></Chapter>
  </Story>;
}

export function IeltsStory() {
  const [task,setTask]=useState(1);
  return <Story next="ielts"><div data-zone="dark"><CaseOpening project="ielts"/><CaseChapters links={[["#why","Learning experience"],["#grading","Feedback design"],["#system","Product decisions"]]}/></div>
    <Chapter id="why" light><Heading n="01 / From practice to progress" title="A place to practise." accent="A reason to return."><p>The product brings exercises, learning material and writing feedback together, so the next useful step is easier to find.</p></Heading><Picture src="/images/ielts-preview.webp" alt="IELTS Studio learning homepage"/><div className={`${s.split} ${s.wide}`}><p className={s.quote}>The score is only useful if the learner knows what to do next.</p><div><h3>Product thinking before implementation.</h3><p>I wanted a learning flow that connected practice to reflection. Original exercises and task-specific feedback became the centre of the experience.</p><Action href="https://ielts-test-kohl.vercel.app/">Explore the learning platform</Action></div></div></Chapter>
    <Chapter id="grading"><Heading n="02 / The judgement behind the feedback" title="One writing test." accent="Different expectations."><p>A report and an argument should not be graded as the same task. The feedback system reflects that distinction.</p></Heading><ScrollArtwork variant="learning"/><div className={s.split}><div><div className={s.tabs}><button aria-pressed={task===1} onClick={()=>setTask(1)}>Writing Task 1</button><button aria-pressed={task===2} onClick={()=>setTask(2)}>Writing Task 2</button></div><h3>{task===1?"Describe what the evidence shows.":"Develop a position and support it."}</h3><p>{task===1?"Task Achievement focuses on an accurate overview and relevant comparisons. An invented opinion does not improve a factual report.":"Task Response looks for a clear position, developed ideas and support that actually addresses the question."}</p></div><div className={s.rubric}><span className={s.label}>Rubric illustration / No generated score</span><h3>{task===1?"Task Achievement":"Task Response"}</h3><p>{task===1?"Overview → selection → comparison":"Position → reasoning → evidence"}</p>{["Coherence & cohesion","Lexical resource","Grammar range & accuracy"].map(x=><div key={x}><span>{x}</span><i/></div>)}</div></div><Process steps={[["Submit","The learner chooses a task and submits their writing."],["Evaluate","A separate rubric guides the assessment for each task."],["Explain","Vietnamese comments make the feedback easier to act on."],["Improve","One priority fix and targeted corrections guide the next draft."]]}/></Chapter>
    <Chapter id="system" light><Heading n="03 / Choices that shape the experience" title="The details are" accent="the product."><p>Behind the interface is a series of decisions about useful feedback, original content and what happens when AI output is imperfect.</p></Heading><Notes rows={[["Calibrated feedback","The grading instructions discourage flattering scores and account for under-length responses and undeveloped arguments. These are design constraints, not a claim of official IELTS score equivalence."],["A structured response","Four criteria, comments, an overall assessment, one next fix and targeted corrections give the interface something consistent to present."],["Original practice content","Exercises are written for this project rather than copied from real exam papers. Distractors test comprehension through paraphrases, corrections and plausible misreadings."],["The implementation","The project uses Next.js, Supabase and an AI grading integration. Structured responses and defensive parsing help the interface handle inconsistent model output."],["What I learned","A working generation endpoint is not enough. The harder work is deciding what good feedback means and designing an experience around that judgement."]]}/><IeltsDiagrams/><div id="learnings" className={s.wide}><Action href="https://ielts-test-kohl.vercel.app/">Try a practice session</Action> <Action href="https://github.com/jak3rpham/Ielts-Test">View the project source</Action></div></Chapter>
  </Story>;
}





